pgerror: allow compiling on wasm
The pgerror library is quite low in the dependency hieararchy. One
problem with it is that it pulls in lib/pq. That library has build tags
which prevent it from being built on wasm. This small patch makes the
pgerror library build for wasm. This is useful so that the protobuf
libraries can now compile to wasm to build introspection tools.

Epic: none

Release note: None